# Generated by Django 6.1 on 2026-08-29 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default="H.B. Trader's", max_length=120)),
                ('tagline', models.CharField(default='Est. Supplier · UP Region', max_length=120)),
                ('subtitle', models.CharField(default='Wholesale & Retail Sanitary Items', max_length=160)),
                ('description', models.TextField(default='We supply sanitary products in both wholesale and retail. We procure directly from manufacturers and distributors, then supply straight to retail shops and customers across the region.')),
                ('address', models.CharField(default='UP, Pharenda, Anand Nagar, Maharajganj', max_length=255)),
                ('phone', models.CharField(default='8114218260', max_length=20)),
                ('email', models.EmailField(default='arslanayan761@gmail.com', max_length=254)),
            ],
            options={
                'verbose_name': 'Business Detail',
                'verbose_name_plural': 'Business Details',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='Catalog position, e.g. 1, 2, 3…', unique=True)),
                ('name', models.CharField(max_length=120)),
                ('sku', models.CharField(blank=True, max_length=40)),
                ('price', models.CharField(blank=True, default='', help_text="Displayed after the ₹ symbol. Leave blank to show '______'.", max_length=40)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('in_stock', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True, help_text='Untick to hide from the catalog without deleting it.')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='ProductSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
                ('value', models.CharField(max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='catalog.product')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
